// Данные пользователей
export const userData = [
  {
    id: 1,
    name: "Ahmad",
    age: 28,
    location: "Tashkent",
    religion: "Muslim",
    education: "Master's Degree",
    occupation: "Software Engineer",
    maritalStatus: "single",
    gender: "male",
    bio: "Looking for a serious relationship to build a family. I value traditional values and am career-oriented.",
    image: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=1974",
    height: 178,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Reading", "Traveling", "Programming"],
    familyValues: ["Traditional", "Family-oriented", "Respectful"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Athletic",
      eyeColor: "Brown",
      hairColor: "Black",
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 2,
      familyStatus: "Middle class",
    },
    preferences: {
      ageRange: { min: 20, max: 28 },
      locationPreference: ["Tashkent", "Samarkand"],
      educationPreference: "Bachelor or higher",
    },
    aboutFamily: "Come from a traditional Uzbek family. Parents are both professionals, and I have two younger siblings.",
    aboutEducation: "Graduated from TUIT with honors. Currently pursuing additional certifications in my field.",
    aboutCareer: "Working as a senior software engineer at a leading tech company. Passionate about technology and innovation.",
    aboutPersonality: "I'm ambitious, kind-hearted, and value honesty above all. I enjoy intellectual conversations and have a good sense of humor.",
    futureGoals: "Planning to start my own tech company while building a loving family. Dream of combining career success with a harmonious family life.",
    additionalImages: [
      "https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=1974",
      "https://images.unsplash.com/photo-1566492031773-4f4e44671857?q=80&w=1974"
    ]
  },
  {
    id: 2,
    name: "Muhammad",
    age: 30,
    location: "Samarkand",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Business Owner",
    maritalStatus: "divorced",
    gender: "male",
    bio: "I'm a business owner who loves to travel and learn about different cultures. Seeking a supportive partner.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1974",
    height: 175,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Traveling", "Reading", "Sports"],
    familyValues: ["Traditional", "Respectful", "Family-oriented"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Fit",
      eyeColor: "Brown",
      hairColor: "Black",
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Middle class",
    },
    preferences: {
      ageRange: { min: 22, max: 30 },
      locationPreference: ["Samarkand", "Tashkent"],
      educationPreference: "Bachelor or higher",
    },
    aboutFamily: "Come from a traditional Uzbek family. Parents are both professionals, and I have one younger sibling.",
    aboutEducation: "Graduated from Samarkand State University with honors. Currently pursuing additional certifications in my field.",
    aboutCareer: "Working as a business owner at a leading company. Passionate about entrepreneurship and innovation.",
    aboutPersonality: "I'm ambitious, kind-hearted, and value honesty above all. I enjoy intellectual conversations and have a good sense of humor.",
    futureGoals: "Planning to expand my business while building a loving family. Dream of combining career success with a harmonious family life.",
    additionalImages: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1974",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1974"
    ]
  },
  {
    id: 3,
    name: "Omar",
    age: 32,
    location: "Bukhara",
    religion: "Muslim",
    education: "PhD",
    occupation: "Professor",
    maritalStatus: "widowed",
    gender: "male",
    bio: "Professor at local university. Seeking a life partner who values education and family.",
    image: "https://images.unsplash.com/photo-1615813967515-e1838c1c5116?q=80&w=1974",
    height: 180,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Reading", "Research", "Teaching"],
    familyValues: ["Traditional", "Respectful", "Family-oriented"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Fit",
      eyeColor: "Brown",
      hairColor: "Black",
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 2,
      familyStatus: "Middle class",
    },
    preferences: {
      ageRange: { min: 25, max: 35 },
      locationPreference: ["Bukhara", "Tashkent"],
      educationPreference: "Master's or higher",
    },
    aboutFamily: "Come from a traditional Uzbek family. Parents are both professionals, and I have two younger siblings.",
    aboutEducation: "Graduated from Bukhara State University with honors. Currently pursuing additional certifications in my field.",
    aboutCareer: "Working as a professor at a local university. Passionate about education and research.",
    aboutPersonality: "I'm ambitious, kind-hearted, and value honesty above all. I enjoy intellectual conversations and have a good sense of humor.",
    futureGoals: "Planning to continue my research while building a loving family. Dream of combining career success with a harmonious family life.",
    additionalImages: [
      "https://images.unsplash.com/photo-1615813967515-e1838c1c5116?q=80&w=1974",
      "https://images.unsplash.com/photo-1615813967515-e1838c1c5116?q=80&w=1974"
    ]
  },
  {
    id: 4,
    name: "Ibrahim",
    age: 29,
    location: "Andijan",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Doctor",
    maritalStatus: "single",
    gender: "male",
    bio: "Medical professional looking for a supportive partner to share life's journey.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1974",
    height: 175,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Reading", "Sports", "Traveling"],
    familyValues: ["Traditional", "Respectful", "Family-oriented"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Fit",
      eyeColor: "Brown",
      hairColor: "Black",
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Middle class",
    },
    preferences: {
      ageRange: { min: 22, max: 30 },
      locationPreference: ["Andijan", "Tashkent"],
      educationPreference: "Bachelor or higher",
    },
    aboutFamily: "Come from a traditional Uzbek family. Parents are both professionals, and I have one younger sibling.",
    aboutEducation: "Graduated from Andijan State Medical Institute with honors. Currently pursuing additional certifications in my field.",
    aboutCareer: "Working as a doctor at a local hospital. Passionate about healthcare and helping others.",
    aboutPersonality: "I'm ambitious, kind-hearted, and value honesty above all. I enjoy intellectual conversations and have a good sense of humor.",
    futureGoals: "Planning to continue my medical career while building a loving family. Dream of combining career success with a harmonious family life.",
    additionalImages: [
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1974",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1974"
    ]
  },
  {
    id: 5,
    name: "Yusuf",
    age: 31,
    location: "Namangan",
    religion: "Muslim",
    education: "Master's Degree",
    occupation: "Architect",
    maritalStatus: "married_second",
    gender: "male",
    bio: "Architect who loves designing both buildings and a beautiful future with the right person.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=1974",
    height: 180,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Designing", "Traveling", "Reading"],
    familyValues: ["Traditional", "Respectful", "Family-oriented"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Fit",
      eyeColor: "Brown",
      hairColor: "Black",
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 2,
      familyStatus: "Middle class",
    },
    preferences: {
      ageRange: { min: 25, max: 35 },
      locationPreference: ["Namangan", "Tashkent"],
      educationPreference: "Master's or higher",
    },
    aboutFamily: "Come from a traditional Uzbek family. Parents are both professionals, and I have two younger siblings.",
    aboutEducation: "Graduated from Namangan State University with honors. Currently pursuing additional certifications in my field.",
    aboutCareer: "Working as an architect at a leading company. Passionate about designing and building.",
    aboutPersonality: "I'm ambitious, kind-hearted, and value honesty above all. I enjoy intellectual conversations and have a good sense of humor.",
    futureGoals: "Planning to continue my architectural career while building a loving family. Dream of combining career success with a harmonious family life.",
    additionalImages: [
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=1974",
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=1974"
    ]
  },
  {
    id: 6,
    name: "Ali",
    age: 27,
    location: "Fergana",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Engineer",
    maritalStatus: "single",
    gender: "male",
    bio: "Engineer with a passion for innovation and creating a loving home.",
    image: "https://images.unsplash.com/photo-1463453091185-61582044d556?q=80&w=1974",
    height: 175,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Innovating", "Traveling", "Reading"],
    familyValues: ["Traditional", "Respectful", "Family-oriented"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Fit",
      eyeColor: "Brown",
      hairColor: "Black",
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Middle class",
    },
    preferences: {
      ageRange: { min: 22, max: 30 },
      locationPreference: ["Fergana", "Tashkent"],
      educationPreference: "Bachelor or higher",
    },
    aboutFamily: "Come from a traditional Uzbek family. Parents are both professionals, and I have one younger sibling.",
    aboutEducation: "Graduated from Fergana State University with honors. Currently pursuing additional certifications in my field.",
    aboutCareer: "Working as an engineer at a leading company. Passionate about innovation and technology.",
    aboutPersonality: "I'm ambitious, kind-hearted, and value honesty above all. I enjoy intellectual conversations and have a good sense of humor.",
    futureGoals: "Planning to continue my engineering career while building a loving family. Dream of combining career success with a harmonious family life.",
    additionalImages: [
      "https://images.unsplash.com/photo-1463453091185-61582044d556?q=80&w=1974",
      "https://images.unsplash.com/photo-1463453091185-61582044d556?q=80&w=1974"
    ]
  },
  {
    id: 7,
    name: "Hassan",
    age: 33,
    location: "Tashkent",
    religion: "Muslim",
    education: "Master's Degree",
    occupation: "Financial Analyst",
    maritalStatus: "divorced",
    gender: "male",
    bio: "Financial analyst seeking a partner who values both career and family.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1974",
    height: 180,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Analyzing", "Traveling", "Reading"],
    familyValues: ["Traditional", "Respectful", "Family-oriented"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Fit",
      eyeColor: "Brown",
      hairColor: "Black",
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 2,
      familyStatus: "Middle class",
    },
    preferences: {
      ageRange: { min: 25, max: 35 },
      locationPreference: ["Tashkent", "Samarkand"],
      educationPreference: "Master's or higher",
    },
    aboutFamily: "Come from a traditional Uzbek family. Parents are both professionals, and I have two younger siblings.",
    aboutEducation: "Graduated from Tashkent State University with honors. Currently pursuing additional certifications in my field.",
    aboutCareer: "Working as a financial analyst at a leading company. Passionate about finance and analysis.",
    aboutPersonality: "I'm ambitious, kind-hearted, and value honesty above all. I enjoy intellectual conversations and have a good sense of humor.",
    futureGoals: "Planning to continue my financial career while building a loving family. Dream of combining career success with a harmonious family life.",
    additionalImages: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1974",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1974"
    ]
  },
  {
    id: 8,
    name: "Umar",
    age: 30,
    location: "Xorazm",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Teacher",
    maritalStatus: "married_second",
    gender: "male",
    bio: "Teacher who believes in the power of education and family values.",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974",
    height: 175,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Teaching", "Traveling", "Reading"],
    familyValues: ["Traditional", "Respectful", "Family-oriented"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Fit",
      eyeColor: "Brown",
      hairColor: "Black",
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Middle class",
    },
    preferences: {
      ageRange: { min: 22, max: 30 },
      locationPreference: ["Xorazm", "Tashkent"],
      educationPreference: "Bachelor or higher",
    },
    aboutFamily: "Come from a traditional Uzbek family. Parents are both professionals, and I have one younger sibling.",
    aboutEducation: "Graduated from Xorazm State University with honors. Currently pursuing additional certifications in my field.",
    aboutCareer: "Working as a teacher at a local school. Passionate about education and helping others.",
    aboutPersonality: "I'm ambitious, kind-hearted, and value honesty above all. I enjoy intellectual conversations and have a good sense of humor.",
    futureGoals: "Planning to continue my teaching career while building a loving family. Dream of combining career success with a harmonious family life.",
    additionalImages: [
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974",
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974"
    ]
  },
  {
    id: 9,
    name: "Fatima",
    age: 25,
    location: "Tashkent",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Teacher",
    maritalStatus: "single",
    gender: "female",
    bio: "Kind-hearted teacher looking for a respectful and family-oriented partner.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1974",
    height: 165,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Teaching", "Traveling", "Reading"],
    familyValues: ["Traditional", "Respectful", "Family-oriented"],
  },
  {
    id: 10,
    name: "Malika",
    age: 25,
    location: "Tashkent",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Fashion Designer",
    maritalStatus: "single",
    gender: "female",
    bio: "Creative soul with a passion for fashion and art. Looking for someone who appreciates beauty in life.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    height: 165,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Fashion Design", "Painting", "Photography"],
    familyValues: ["Modern", "Family-oriented", "Creative"],
    religiousLevel: "Moderate",
    prayer: "Regular",
    smoking: "Never",
    income: "Average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Slim",
      eyeColor: "Brown",
      hairColor: "Black"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 2,
      familyStatus: "Middle class"
    },
    preferences: {
      ageRange: { min: 25, max: 35 },
      locationPreference: ["Tashkent"],
      educationPreference: "Bachelor or higher"
    },
    aboutFamily: "From a loving family that supports my creative pursuits",
    aboutEducation: "Graduated from National Institute of Arts and Design",
    aboutCareer: "Running my own fashion design studio",
    aboutPersonality: "Creative, passionate, and caring person who values authenticity",
    futureGoals: "Want to expand my fashion brand while creating a loving family",
    additionalImages: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330"
    ]
  },
  {
    id: 11,
    name: "Sabina",
    age: 27,
    location: "Samarkand",
    religion: "Muslim",
    education: "Master's Degree",
    occupation: "Doctor",
    maritalStatus: "single",
    gender: "female",
    bio: "Dedicated doctor looking for a supportive partner who values both career and family.",
    image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce",
    height: 168,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Reading", "Cooking", "Yoga"],
    familyValues: ["Traditional", "Caring", "Balanced"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: false,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Athletic",
      eyeColor: "Brown",
      hairColor: "Brown"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Upper middle class"
    },
    preferences: {
      ageRange: { min: 27, max: 35 },
      locationPreference: ["Samarkand", "Tashkent"],
      educationPreference: "Master's or higher"
    },
    aboutFamily: "Come from a family of medical professionals",
    aboutEducation: "Graduated from Samarkand Medical Institute",
    aboutCareer: "Working as a pediatrician in a private clinic",
    aboutPersonality: "Compassionate, dedicated, and loving person",
    futureGoals: "Balance successful medical career with happy family life",
    additionalImages: [
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce",
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce"
    ]
  },
  {
    id: 12,
    name: "Zarina",
    age: 24,
    location: "Bukhara",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Teacher",
    maritalStatus: "single",
    gender: "female",
    bio: "Kind-hearted teacher who loves children and values education.",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
    height: 162,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian"],
    hobbies: ["Teaching", "Reading", "Gardening"],
    familyValues: ["Traditional", "Nurturing", "Patient"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Average",
    livingArrangement: "With family",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Average",
      eyeColor: "Brown",
      hairColor: "Black"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 3,
      familyStatus: "Middle class"
    },
    preferences: {
      ageRange: { min: 24, max: 32 },
      locationPreference: ["Bukhara", "Tashkent"],
      educationPreference: "Bachelor or higher"
    },
    aboutFamily: "Close-knit traditional family with strong values",
    aboutEducation: "Graduated from Bukhara State University",
    aboutCareer: "Primary school teacher passionate about education",
    aboutPersonality: "Patient, kind, and great with children",
    futureGoals: "Create a loving home while continuing to educate young minds",
    additionalImages: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1"
    ]
  },
  {
    id: 13,
    name: "Dilnoza",
    age: 26,
    location: "Tashkent",
    religion: "Muslim",
    education: "Master's Degree",
    occupation: "Architect",
    maritalStatus: "single",
    gender: "female",
    bio: "Creative architect with a passion for sustainable design and modern aesthetics.",
    image: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df",
    height: 170,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Architecture", "Sketching", "Travel"],
    familyValues: ["Modern", "Ambitious", "Caring"],
    religiousLevel: "Moderate",
    prayer: "Sometimes",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Slim",
      eyeColor: "Brown",
      hairColor: "Black"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Upper middle class"
    },
    preferences: {
      ageRange: { min: 26, max: 35 },
      locationPreference: ["Tashkent"],
      educationPreference: "Bachelor or higher"
    },
    aboutFamily: "Modern family that encourages professional growth",
    aboutEducation: "Master's in Architecture from Turin Polytechnic University",
    aboutCareer: "Working at leading architectural firm",
    aboutPersonality: "Creative, detail-oriented, and ambitious",
    futureGoals: "Establish my own architectural firm while building a family",
    additionalImages: [
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df",
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df"
    ]
  },
  {
    id: 14,
    name: "Nilufar",
    age: 28,
    location: "Fergana",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Business Analyst",
    maritalStatus: "single",
    gender: "female",
    bio: "Analytical mind with a warm heart, seeking a partner who values both intelligence and emotion.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
    height: 167,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Analytics", "Chess", "Swimming"],
    familyValues: ["Balance", "Growth", "Support"],
    religiousLevel: "Moderate",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Athletic",
      eyeColor: "Brown",
      hairColor: "Brown"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 2,
      familyStatus: "Middle class"
    },
    preferences: {
      ageRange: { min: 28, max: 36 },
      locationPreference: ["Fergana", "Tashkent"],
      educationPreference: "Bachelor or higher"
    },
    aboutFamily: "Supportive family that values education and career",
    aboutEducation: "Economics degree from Fergana State University",
    aboutCareer: "Senior Business Analyst at consulting firm",
    aboutPersonality: "Analytical, empathetic, and goal-oriented",
    futureGoals: "Advance in career while creating a loving family",
    additionalImages: [
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb"
    ]
  },
  {
    id: 15,
    name: "Kamila",
    age: 23,
    location: "Tashkent",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Marketing Specialist",
    maritalStatus: "single",
    gender: "female",
    bio: "Young professional with creative mindset and traditional values.",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
    height: 165,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Digital Marketing", "Photography", "Cooking"],
    familyValues: ["Traditional", "Modern outlook", "Family-oriented"],
    religiousLevel: "Moderate",
    prayer: "Regular",
    smoking: "Never",
    income: "Average",
    livingArrangement: "With family",
    willingToRelocate: false,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Slim",
      eyeColor: "Brown",
      hairColor: "Black"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 2,
      familyStatus: "Middle class"
    },
    preferences: {
      ageRange: { min: 23, max: 30 },
      locationPreference: ["Tashkent"],
      educationPreference: "Bachelor or higher"
    },
    aboutFamily: "Close family with blend of traditional and modern values",
    aboutEducation: "Marketing degree from Westminster University",
    aboutCareer: "Digital Marketing Specialist at tech company",
    aboutPersonality: "Creative, sociable, and family-oriented",
    futureGoals: "Build successful career in marketing while starting a family",
    additionalImages: [
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"
    ]
  },
  {
    id: 16,
    name: "Aziza",
    age: 29,
    location: "Namangan",
    religion: "Muslim",
    education: "PhD",
    occupation: "Research Scientist",
    maritalStatus: "single",
    gender: "female",
    bio: "Dedicated researcher in biochemistry, looking for an intellectual partner.",
    image: "https://images.unsplash.com/photo-1557555187-23d685287bc3",
    height: 169,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Research", "Reading", "Classical Music"],
    familyValues: ["Education", "Growth", "Balance"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Average",
      eyeColor: "Brown",
      hairColor: "Black"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Academic"
    },
    preferences: {
      ageRange: { min: 29, max: 38 },
      locationPreference: ["Namangan", "Tashkent"],
      educationPreference: "Master's or higher"
    },
    aboutFamily: "Academic family background with focus on education",
    aboutEducation: "PhD in Biochemistry from National University",
    aboutCareer: "Research Scientist at medical research institute",
    aboutPersonality: "Intellectual, curious, and kind-hearted",
    futureGoals: "Continue research while building a family with shared values",
    additionalImages: [
      "https://images.unsplash.com/photo-1557555187-23d685287bc3",
      "https://images.unsplash.com/photo-1557555187-23d685287bc3"
    ]
  },
  {
    id: 17,
    name: "Madina",
    age: 25,
    location: "Andijan",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Nurse",
    maritalStatus: "single",
    gender: "female",
    bio: "Caring nurse with a gentle soul, seeking a kind-hearted partner.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
    height: 163,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian"],
    hobbies: ["Healthcare", "Volunteering", "Cooking"],
    familyValues: ["Traditional", "Caring", "Supportive"],
    religiousLevel: "Practicing",
    prayer: "Regular",
    smoking: "Never",
    income: "Average",
    livingArrangement: "With family",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Average",
      eyeColor: "Brown",
      hairColor: "Brown"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 3,
      familyStatus: "Middle class"
    },
    preferences: {
      ageRange: { min: 25, max: 33 },
      locationPreference: ["Andijan", "Tashkent"],
      educationPreference: "Bachelor or higher"
    },
    aboutFamily: "Warm and traditional family with strong values",
    aboutEducation: "Nursing degree from Andijan Medical Institute",
    aboutCareer: "Dedicated nurse at city hospital",
    aboutPersonality: "Compassionate, patient, and caring",
    futureGoals: "Continue helping others while raising a loving family",
    additionalImages: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2"
    ]
  },
  {
    id: 18,
    name: "Sevara",
    age: 26,
    location: "Tashkent",
    religion: "Muslim",
    education: "Master's Degree",
    occupation: "Financial Analyst",
    maritalStatus: "single",
    gender: "female",
    bio: "Finance professional with a love for arts and culture.",
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f",
    height: 166,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Finance", "Art Galleries", "Piano"],
    familyValues: ["Modern", "Cultural", "Ambitious"],
    religiousLevel: "Moderate",
    prayer: "Sometimes",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: false,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Slim",
      eyeColor: "Brown",
      hairColor: "Black"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Upper middle class"
    },
    preferences: {
      ageRange: { min: 26, max: 34 },
      locationPreference: ["Tashkent"],
      educationPreference: "Bachelor or higher"
    },
    aboutFamily: "Cultured family with appreciation for arts",
    aboutEducation: "Master's in Finance from Singapore University",
    aboutCareer: "Senior Financial Analyst at international bank",
    aboutPersonality: "Analytical, cultured, and ambitious",
    futureGoals: "Advance in finance while maintaining cultural interests",
    additionalImages: [
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f",
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f"
    ]
  },
  {
    id: 19,
    name: "Umida",
    age: 24,
    location: "Tashkent",
    religion: "Muslim",
    education: "Bachelor's Degree",
    occupation: "Software Developer",
    maritalStatus: "single",
    gender: "female",
    bio: "Tech-savvy developer with a creative side, looking for understanding partner.",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    height: 168,
    nationality: "Uzbek",
    languages: ["Uzbek", "Russian", "English"],
    hobbies: ["Coding", "Digital Art", "Gaming"],
    familyValues: ["Modern", "Independent", "Supportive"],
    religiousLevel: "Moderate",
    prayer: "Sometimes",
    smoking: "Never",
    income: "Above average",
    livingArrangement: "Own apartment",
    willingToRelocate: true,
    hasChildren: false,
    wantsChildren: true,
    physicalAppearance: {
      bodyType: "Athletic",
      eyeColor: "Brown",
      hairColor: "Black"
    },
    familyBackground: {
      parents: "Both alive",
      siblings: 1,
      familyStatus: "Middle class"
    },
    preferences: {
      ageRange: { min: 24, max: 32 },
      locationPreference: ["Tashkent"],
      educationPreference: "Bachelor or higher"
    },
    aboutFamily: "Modern family supporting women in tech",
    aboutEducation: "Computer Science degree from INHA University",
    aboutCareer: "Full-stack developer at tech startup",
    aboutPersonality: "Tech-savvy, creative, and independent",
    futureGoals: "Create innovative tech solutions while building a modern family",
    additionalImages: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9"
    ]
  }
]

// Функции для фильтрации по полу
export const getMenData = () => {
  return userData.filter(user => user.gender === 'male')
}

export const getWomenData = () => {
  return userData.filter(user => user.gender === 'female')
}
